# Generated by Django 4.2.28 on 2026-02-24 23:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
